# Generated by Django 4.0.2 on 2022-03-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
